"""описание изменений

Revision ID: 03a9e3c61add
Revises: 20251125_add_geo_and_fields
Create Date: 2025-11-25 14:14:43.232427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a9e3c61add'
down_revision: Union[str, None] = '20251125_add_geo_and_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
